"""Setup script for dorina-agent."""
from setuptools import setup, find_packages

setup(
    name="dorina-agent",
    version="1.0.0",
    description="Self-hosted CLI AI agent with 65+ tools, 23 providers, multi-model support, and self-testing",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="Talha Atalha Tülü",
    author_email="talha@atalhatulu.com",
    url="https://github.com/atalhatulu/dorina-agent",
    license="MIT",
    packages=find_packages(exclude=["tests*", "docs*"]),
    include_package_data=True,
    entry_points={
        "console_scripts": [
            "dorina=main:entry",
        ],
    },
    python_requires=">=3.10",
    install_requires=[
        "litellm>=1.60.0",
        "rich>=13.0.0",
        "prompt-toolkit>=3.0.0",
        "pyyaml>=6.0",
        "python-dotenv>=1.0.0",
        "pydantic>=2.5.0",
        "pydantic-settings>=2.1.0",
        "httpx>=0.27.0",
        "beautifulsoup4>=4.12.0",
        "markdown>=3.5.0",
        "pygments>=2.17.0",
        "sqlalchemy>=2.0.0",
        "ddgs>=1.0.0",
        "chromadb>=0.6.0",
        "fastembed>=0.5.0",
        "playwright>=1.50.0",
        "docker>=7.0.0",
        "tiktoken>=0.9.0",
        "pillow>=10.0.0",
    ],
    extras_require={
        "dev": ["pytest>=8.0.0", "pytest-asyncio>=0.25.0", "pytest-cov>=5.0.0"],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
    ],
)
